// Language extensions to highlight.js language name mapping
export const EXTENSION_TO_LANGUAGE: Record<string, string> = {
  js: 'javascript',
  jsx: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  py: 'python',
  rb: 'ruby',
  go: 'go',
  rs: 'rust',
  java: 'java',
  kt: 'kotlin',
  swift: 'swift',
  c: 'c',
  cpp: 'cpp',
  cs: 'csharp',
  php: 'php',
  html: 'html',
  htm: 'html',
  css: 'css',
  scss: 'scss',
  sass: 'scss',
  json: 'json',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'ini',
  xml: 'xml',
  md: 'markdown',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'bash',
  sql: 'sql',
  dockerfile: 'dockerfile',
  graphql: 'graphql',
  gql: 'graphql',
  proto: 'protobuf',
  lua: 'lua',
  r: 'r',
  m: 'objectivec',
  mm: 'objectivec',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hrl: 'erlang',
  hs: 'haskell',
  lhs: 'haskell',
  scala: 'scala',
  clj: 'clojure',
  cljs: 'clojure',
  coffee: 'coffeescript',
  dart: 'dart',
  vue: 'xml',
  svelte: 'xml',
  tf: 'hcl',
  hcl: 'hcl',
  nix: 'nix',
};

export const POPULAR_LANGUAGES = [
  'javascript',
  'typescript',
  'python',
  'go',
  'rust',
  'java',
  'kotlin',
  'swift',
  'c',
  'cpp',
  'csharp',
  'php',
  'ruby',
  'html',
  'css',
  'json',
  'yaml',
  'markdown',
  'bash',
  'sql',
  'dockerfile',
  'graphql',
  'scala',
  'dart',
  'lua',
];

export const LANGUAGE_LABELS: Record<string, string> = {
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  python: 'Python',
  go: 'Go',
  rust: 'Rust',
  java: 'Java',
  kotlin: 'Kotlin',
  swift: 'Swift',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  php: 'PHP',
  ruby: 'Ruby',
  html: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  json: 'JSON',
  yaml: 'YAML',
  markdown: 'Markdown',
  bash: 'Bash / Shell',
  sql: 'SQL',
  dockerfile: 'Dockerfile',
  graphql: 'GraphQL',
  scala: 'Scala',
  dart: 'Dart',
  lua: 'Lua',
  r: 'R',
  elixir: 'Elixir',
  erlang: 'Erlang',
  haskell: 'Haskell',
  coffeescript: 'CoffeeScript',
  objectivec: 'Objective-C',
  clojure: 'Clojure',
};

export function getLanguageFromFilename(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase() ?? '';
  if (filename.toLowerCase() === 'dockerfile') return 'dockerfile';
  if (filename.toLowerCase() === 'makefile') return 'makefile';
  return EXTENSION_TO_LANGUAGE[ext] ?? 'plaintext';
}

export function getLanguageLabel(lang: string | null): string {
  if (!lang) return 'Text';
  const normalized = lang.toLowerCase();
  return LANGUAGE_LABELS[normalized] ?? lang;
}

export function getLanguageColor(lang: string | null): string {
  const colors: Record<string, string> = {
    javascript: '#F7DF1E',
    typescript: '#3178C6',
    python: '#3572A5',
    go: '#00ADD8',
    rust: '#DEA584',
    java: '#B07219',
    kotlin: '#A97BFF',
    swift: '#FA7343',
    c: '#555555',
    cpp: '#F34B7D',
    csharp: '#239120',
    php: '#4F5D95',
    ruby: '#701516',
    html: '#E34C26',
    css: '#563D7C',
    json: '#292929',
    yaml: '#CB171E',
    markdown: '#083FA1',
    bash: '#89E051',
    sql: '#E38C00',
    dockerfile: '#384D54',
  };
  const normalized = (lang ?? '').toLowerCase();
  return colors[normalized] ?? '#8B949E';
}
